# First build, then test the package install is working.
stages:
  - build
  - test-install
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - |
#    - export giturl="https://github.com/zoobab/openwrt_helloworld"
#    - export packname="helloworld"
#    - export sdk_image="zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
    - docker build --output type=local,dest=artifacts --build-arg GIT_URL="$GIT_URL" --build-arg PACK_NAME="$PACK_NAME" --build-arg SDK_IMAGE="$SDK_IMAGE" .
    - apk update
    - apk add curl
    - cd "artifacts/${UPLOAD_SOURCE}"
    - for file in *; do curl --user "usernameisnotimportant:${PERSONAL_ACCESS_TOKEN}" --upload-file $file "https://${UPLOAD_REPO}/${file}"; done

  artifacts:
    paths:
      - artifacts/
test-install:
  image: debian:latest
  stage: test-install
  script:
    - dpkg --add-architecture "${DPKG_ARCH}"
    - apt update
    - apt install -y curl binfmt-support qemu-user-static "libc6:${DPKG_ARCH}"
    - curl -L "https://downloads.openwrt.org/releases/22.03.5/targets/${ARCH}/${SUBARCH}/openwrt-22.03.5-${ARCH}-${SUBARCH}-rootfs.tar.gz" -o rootfs.tar.gz
    - tar -xpf rootfs.tar.gz
    - chroot . /bin/sh -c "sed -i 's/https/http/g' /etc/opkg/distfeeds.conf"
    - chroot . /bin/sh -c "sed -i '/check_signature/s/^/#/g' /etc/opkg.conf"
    - chroot . /bin/sh -c "mkdir -p /var/lock/ && touch /var/lock/opkg.lock"
    - rm -f ./etc/resolv.conf && cp /etc/resolv.conf ./etc/resolv.conf
    - chroot . /bin/sh -c "opkg update"
    - chroot . /bin/sh -c "opkg install wget-ssl"
    - chroot . /bin/sh -c "echo 'src/gz myrepo http://usernameisnotimportant:${PERSONAL_ACCESS_TOKEN}@${UPLOAD_REPO}' >> /etc/opkg/customfeeds.conf"
    - chroot . /bin/sh -c "opkg update"
    - chroot . /bin/sh -c "opkg install '${PACK_NAME}'"
    # Optionally run PACK_NAME
    - chroot . /bin/sh -c "'${PACK_NAME}'"

variables:
  PACK_NAME:
    description: "Name of the package directory inside the git repo"
    value: "helloworld"
  GIT_URL:
    description: "GIT URL"
    value: "https://github.com/zoobab/openwrt_helloworld"
  UPLOAD_SOURCE:
    description: "The source folder to upload artifacts from"
    value: "packages/x86_64/myrepo/"
  UPLOAD_REPO:
    description: "The GitLab generic package repo to push to"
    value: "gitlab.com/api/v4/projects/${GITLAB_USER_NAME}%2Fopenwrtsdkbuild/packages/generic/x86_64/0.0.2/"
  SDK_IMAGE:
    description: "SDK Docker Image"
    value: "zoobab/openwrtsdk:21.02.0-rc4-x86-64"
    options:
      - "zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
      - "zoobab/openwrtsdk:21.02.0-rc4-imx6-generic"
      - "zoobab/openwrtsdk:21.02.0-rc4-bcm27xx-bcm2708"
      - "zoobab/openwrtsdk:21.02.0-rc4-x86-64"
  QEMU_ARCH:
    description: "Architecture specification, in qemu format"
    value: "x86_64"
  DPKG_ARCH:
   description: "Architecture specification, in debian format"
   value: "amd64"
  ARCH:
    description: "Architecture specification, in openwrt format"
    value: "x86"
  SUBARCH:
    description: "Subarchitecture specification, in openwrt format"
    value: "64"
