docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - |
#    - export giturl="https://github.com/zoobab/openwrt_helloworld"
#    - export packname="helloworld"
#    - export sdk_image="zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
    - docker build --output type=local,dest=artifacts --build-arg GIT_URL="$GIT_URL" --build-arg PACK_NAME="$PACK_NAME" --build-arg SDK_IMAGE="$SDK_IMAGE" .
  artifacts:
    paths:
      - artifacts/

variables:
  PACK_NAME:
    description: "Name of the package directory inside the git repo"
    value: "helloworld"
  GIT_URL:
    description: "GIT URL"
    value: "https://github.com/zoobab/openwrt_helloworld"
  SDK_IMAGE:
    description: "SDK Docker Image"
    value: "zoobab/openwrtsdk:21.02.0-rc4-x86_64"
    options: 
      - "zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
      - "zoobab/openwrtsdk:21.02.0-rc4-imx6-generic"
      - "zoobab/openwrtsdk:21.02.0-rc4-bcm27xx-bcm2708"
