docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - |
    - export giturl="https://github.com/zoobab/openwrt_helloworld"
    - export packname="helloworld"
    - export sdk_image="zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
    - docker build --output type=local,dest=artifacts --build-arg giturl="$giturl" --build-arg packname="$packname" --build-arg sdk_image="$arch" .
  artifacts:
    paths:
      - artifacts/
