docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - |
#    - export giturl="https://github.com/zoobab/openwrt_helloworld"
#    - export packname="helloworld"
#    - export sdk_image="zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
    - docker build --output type=local,dest=artifacts --build-arg GIT_URL="$GIT_URL" --build-arg PACK_NAME="$PACK_NAME" --build-arg SDK_IMAGE="$SDK_IMAGE" .
    - apk update
    - apk add git
    - apk add openssh
    - echo ${CI_SECURE_SHELL} > /tmp/sshkey
    - ssh-add /tmp/sshkey
    - git clone "https://${UPLOAD_PATH}" upload
    - cp -r artifacts/* upload
    - cd upload
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git add . && git commit -m "$(date)"
    - git remote set-url --push origin "${UPLOAD_PATH}"

  artifacts:
    paths:
      - artifacts/

variables:
  PACK_NAME:
    description: "Name of the package directory inside the git repo"
    value: "helloworld"
  GIT_URL:
    description: "GIT URL"
    value: "https://github.com/zoobab/openwrt_helloworld"
  UPLOAD_PATH:
    description: "The GitLab repository to push to. Please edit this to your username, it won't be able to upload artifacts outside otherwise!"
    value: "git@gitlab.com:ndren/openwrtrepo.git"
  SDK_IMAGE:
    description: "SDK Docker Image"
    value: "zoobab/openwrtsdk:21.02.0-rc4-x86-64"
    options: 
      - "zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
      - "zoobab/openwrtsdk:21.02.0-rc4-imx6-generic"
      - "zoobab/openwrtsdk:21.02.0-rc4-bcm27xx-bcm2708"
      - "zoobab/openwrtsdk:21.02.0-rc4-x86-64"
