docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - |
    - export giturl="https://github.com/zoobab/openwrt_helloworld"
    - export packname="helloworld"
    - export arch="x86"
    - export subarch="64"
    - export relver="21.02.0-rc4"
    - docker build --output type=local,dest=artifacts --build-arg giturl="$giturl" --build-arg packname="$packname" --build-arg arch="$arch" --build-arg subarch="$subarch" --build-arg relver="$relver" .
  artifacts:
    paths:
      - artifacts/
