docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - |
#    - export giturl="https://github.com/zoobab/openwrt_helloworld"
#    - export packname="helloworld"
#    - export sdk_image="zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
    - docker build --output type=local,dest=artifacts --build-arg GIT_URL="$GIT_URL" --build-arg PACK_NAME="$PACK_NAME" --build-arg SDK_IMAGE="$SDK_IMAGE" .
    - apk update
    - apk add curl
    - cd "artifacts/${UPLOAD_SOURCE}"
    - for file in *; do curl --user "usernameisnotimportant:${PERSONAL_ACCESS_TOKEN}" --upload-file $file "${UPLOAD_REPO}/${file}"; done

  artifacts:
    paths:
      - artifacts/

variables:
  PACK_NAME:
    description: "Name of the package directory inside the git repo"
    value: "helloworld"
  GIT_URL:
    description: "GIT URL"
    value: "https://github.com/zoobab/openwrt_helloworld"
  UPLOAD_SOURCE:
    description: "The source folder to upload artifacts from"
    value: "packages/x86_64/"
  UPLOAD_REPO:
    description: "The GitLab generic package repo to push to"
    value: "https://gitlab.com/api/v4/projects/${GITLAB_USER_NAME}%2Fopenwrtsdkbuild/packages/generic/x86_64/0.0.2/"
  SDK_IMAGE:
    description: "SDK Docker Image"
    value: "zoobab/openwrtsdk:21.02.0-rc4-x86-64"
    options:
      - "zoobab/openwrtsdk:21.02.0-rc4-sunxi-cortexa53"
      - "zoobab/openwrtsdk:21.02.0-rc4-imx6-generic"
      - "zoobab/openwrtsdk:21.02.0-rc4-bcm27xx-bcm2708"
      - "zoobab/openwrtsdk:21.02.0-rc4-x86-64"
