name: Package Building

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GIT_URL: "https://github.com/zoobab/openwrt_helloworld"
  PACK_NAME: "helloworld"
  SDK_IMAGE: "andreien/openwrtsdk:22.03.5-armvirt-64"
  UPLOAD_REPO: "https://github.com/ndren/openwrtsdkbuild"
  #IPK_PATTERN: 'helloworld_1.0-1_$ARCH.ipk'
  OPENWRT_ROOTFS_TAG: "aarch64_cortex-a53-23.05.0-rc1"
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        for ARCH_SPEC in $(sed '/^#/d' architecture-map)
        do
          SDK_IMAGE=$(echo "$ARCH_SPEC" | cut -d'|' -f1)
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=artifacts --build-arg GIT_URL="$GIT_URL" --build-arg PACK_NAME="$PACK_NAME" --build-arg SDK_IMAGE="$SDK_IMAGE" .
        done
        
        find /home/runner/work/openwrtsdkbuild/openwrtsdkbuild/artifacts/packages/*/*/*.ipk
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Package release"
        files: |
            /home/runner/work/openwrtsdkbuild/openwrtsdkbuild/artifacts/packages/*/*/*.ipk
      
  test:
  
    needs: build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - name: Test the Docker image
      run: |
        for ARCH_SPEC in $(sed '/^#/d' architecture-map)
        do
          ROOTFS_IMAGE=$(echo "$ARCH_SPEC" | cut -d'|' -f2)
          ARCH=$(echo "$ARCH_SPEC" | cut -d'|' -f3)
          IPK_PATTERN='helloworld_1.0-1_$ARCH.ipk'
          eval "IPK_NAME=$IPK_PATTERN"
          docker run -e UPLOAD_REPO -e IPK_NAME -e PACK_NAME "${ROOTFS_IMAGE}" /bin/sh -c "$(cat test-gh-release.sh)"
        done
