name: Package Building

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GIT_URL: "https://github.com/zoobab/openwrt_helloworld"
  PACK_NAME: "helloworld"
  SDK_IMAGE: "andreien/openwrtsdk:22.03.5-armvirt-64"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build --output type=local,dest=artifacts --build-arg GIT_URL="$GIT_URL" --build-arg PACK_NAME="$PACK_NAME" --build-arg SDK_IMAGE="$SDK_IMAGE" .
        find artifacts
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Package release"
        files: |
            artifacts/packages/*/*/*.ipk
      
  test:
  
    needs: build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test the Docker image
      run: docker run -e PERSONAL_ACCESS_TOKEN -e UPLOAD_REPO -e PACK_NAME --platform "${DOCKER_PLATFORM}" "openwrt/rootfs:${OPENWRT_ROOTFS_TAG}" /bin/sh -c "$(cat ci-test-install.sh)"
